version: '3.8'

services:
  postgres:
    image: postgres:latest  # Specify the desired PostgreSQL version
    container_name: postgres
    environment:
      POSTGRES_DB: product_catagory  # Replace with your database name
      POSTGRES_USER: postgres     # Replace with your PostgreSQL username
      POSTGRES_PASSWORD: postgres  # Replace with your PostgreSQL password
    ports:
      - "5432:5432"  # Map PostgreSQL port
      #volumes:
      #- postgres_data:/var/lib/postgresql/data  # Persist PostgreSQL data

  pgadmin:
    image: dpage/pgadmin4:latest  # Use the latest pgAdmin image
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com  # Replace with your pgAdmin email
      PGADMIN_DEFAULT_PASSWORD: admin  # Replace with your pgAdmin password
    ports:
      - "80:80"  # Map pgAdmin port to localhost
    depends_on:
      - postgres